include:
  - local: terraform/network/.gitlab-ci.yaml
  - local: terraform/eks-cluster/.gitlab-ci.yaml
  - local: terraform/ec2-vault/.gitlab-ci.yaml
  - local: terraform/ec2-gitlab-runner/.gitlab-ci.yaml
  - local: terraform/ecr-htht/.gitlab-ci.yaml
