variables:
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"
  TF_ROOT: terraform/ec2-gitlab-runner

before_script:
  - cd $TF_ROOT
  - terraform --version
  - terraform init

stages:
  - validation
  - planning
  - action

Config files Validation_for_runner:
  stage: validation
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ec2-gitlab-runner/**/*
      when: always
    - when: never
  script:
    - terraform validate

planning_for_runner:
  stage: planning
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ec2-gitlab-runner/**/*
      when: always
    - when: never
  script:
    - terraform plan

apply_job_for_runner:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "apply"'
      changes:
        - terraform/ec2-gitlab-runner/**/*
      when: manual
    - when: never
  script:
    - terraform apply -auto-approve

destroy_job_for_runner:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "destroy"'
      changes:
        - terraform/ec2-gitlab-runner/**/*
      when: manual
    - when: never
  script:
    - terraform destroy -auto-approve
