workflow:
  rules:
    - changes:
        - terraform/eks-cluster/**/*
      when: always
    - when: never

variables:
  ENV: secret
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"



before_script:
  - terraform --version
  - export VAULT_SKIP_VERIFY=true
  - |
    VAULT_TOKEN=$(vault write -field=token \
      auth/approle/login \
      role_id=$VAULT_ROLE_ID \
      secret_id=$VAULT_SECRET_ID)
    export VAULT_TOKEN
  - terraform init

stages:
  - validation
  - planning
  - action

Config files Validation_for_eks:
  stage: validation
  tags:
    - terraform
  script:
    - terraform validate


planning_for_eks:
  stage: planning
  tags:
   - terraform
  script:
   - vault kv get -format=json secret/terraform/eks | \
     jq -r '.data.data | to_entries[] | "\(.key)=\"\(.value)\""' > $ENV.tfvars
   - terraform plan -var-file="$ENV.tfvars"

apply_job_for_eks:
  stage: action
  tags:
    - terraform
  script:

    - if [[ "$TERRAFORM_ACTION" == "apply" ]]; then

          vault kv get -format=json secret/terraform/eks | \
          jq -r '.data.data | to_entries[] | "\(.key)=\"\(.value)\""' > $ENV.tfvars
          terraform apply -auto-approve -var-file="$ENV.tfvars"
      fi
  when: manual

  only:
    variables:
     - $TERRAFORM_ACTION == "apply"

destroy_job_for_eks:
  stage: action
  tags:
   - terraform
  script:
   - if [[ "$TERRAFORM_ACTION" == "destroy" ]]; then

          vault kv get -format=json secret/terraform/eks | \
          jq -r '.data.data | to_entries[] | "\(.key)=\"\(.value)\""' > $ENV.tfvars
          terraform destroy -auto-approve -var-file="$ENV.tfvars"
      fi
  when: manual

  only:
    variables:
     - $TERRAFORM_ACTION == "destroy"

