variables:
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"

before_script:
  - terraform --version
  - terraform init

stages:
  - validation
  - planning
  - action

Config files Validation_for_ecr:
  stage: validation
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ecr-htht/**/*
      when: always
    - when: never
  script:
    - terraform validate

planning_for_ecr:
  stage: planning
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ecr-htht/**/*
      when: always
    - when: never
  script:
    - terraform plan

apply_job_for_ecr:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "apply"'
      changes:
        - terraform/ecr-htht/**/*
      when: manual
    - when: never
  script:
    - terraform apply -auto-approve

destroy_job_for_ecr:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "destroy"'
      changes:
        - terraform/ecr-htht/**/*
      when: manual
    - when: never
  script:
    - terraform destroy -auto-approve
