variables:
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"

stages:
  - validation
  - planning
  - action

Config files Validation_for_ecr:
  stage: validation
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ecr-htht/**/*
      when: always
    - when: never
  before_script:
    - cd terraform/ecr-htht
    - terraform --version
    - terraform init
  script:
    - terraform validate

planning_for_ecr:
  stage: planning
  tags:
    - terraform
  rules:
    - changes:
        - terraform/ecr-htht/**/*
      when: always
    - when: never
  before_script:
    - cd terraform/ecr-htht
    - terraform --version
    - terraform init
  script:
    - terraform plan

apply_job_for_ecr:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "apply"'
      changes:
        - terraform/ecr-htht/**/*
      when: manual
    - when: never
  before_script:
    - cd terraform/ecr-htht
    - terraform --version
    - terraform init
  script:
    - terraform apply -auto-approve

destroy_job_for_ecr:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "destroy"'
      changes:
        - terraform/ecr-htht/**/*
      when: manual
    - when: never
  before_script:
    - cd terraform/ecr-htht
    - terraform --version
    - terraform init
  script:
    - terraform destroy -auto-approve
