apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/address: "https://10.0.0.11:8200"
        vault.hashicorp.com/tls-skip-verify: "true"  
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          MONGO_INITDB_ROOT_USERNAME="{{ .Data.data.username }}"
          MONGO_INITDB_ROOT_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
