variables:
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"
  VAULT_ADDR: "https://10.0.0.11:8200"

stages:
  - validation
  - planning
  - action

Config files Validation for_network:
  stage: validation
  tags:
    - terraform
  rules:
    - changes:
        - terraform/network/**/*
      when: always
    - when: never
  before_script:
    - cd terraform/network
    - terraform --version
    - terraform init
  script:
    - terraform validate

planning_for_network:
  stage: planning
  tags:
    - terraform
  rules:
    - changes:
        - terraform/network/**/*
      when: always
    - when: never
  before_script:
    - cd terraform/network
    - terraform --version
    - VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)
    - export VAULT_TOKEN
    - terraform init
  script:
    - vault kv get -format=json secret/terraform/network | jq -r '.data.data | to_entries[] | "\(.key)=\(.value | tojson)"' > $ENV.tfvars
    - terraform plan -var-file="secret.tfvars"

apply_job_for_network:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "apply"'
      changes:
        - terraform/network/**/*
      when: manual
    - when: never
  before_script:
    - cd terraform/network
    - terraform --version
    - VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)
    - export VAULT_TOKEN
    - terraform init
  script:
    - vault kv get -format=json secret/terraform/network | jq -r '.data.data | to_entries[] | "\(.key)=\(.value | tojson)"' > $ENV.tfvars
    - terraform apply -auto-approve -var-file="$ENV.tfvars"

destroy_job_for_network:
  stage: action
  tags:
    - terraform
  rules:
    - if: '$TERRAFORM_ACTION == "destroy"'
      changes:
        - terraform/network/**/*
      when: manual
    - when: never
  before_script:
    - cd terraform/network
    - terraform --version
    - VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)
    - export VAULT_TOKEN
    - terraform init
  script:
    - vault kv get -format=json secret/terraform/network | jq -r '.data.data | to_entries[] | "\(.key)=\(.value | tojson)"' > $ENV.tfvars
    - terraform destroy -auto-approve -var-file="$ENV.tfvars"
