workflow:
  rules:
    - changes:
        - terraform/ec2-vault/**/*
      when: always
    - when: never


variables:
  TERRAFORM_ACTION: apply
  TF_IN_AUTOMATION: "true"

before_script:
  - terraform --version
  - terraform init

stages:
  - validation
  - planning
  - action

Config files Validation_for_vault:
  stage: validation
  tags:
    - terraform
  script:
    - terraform validate

planning_for_vault:
  stage: planning
  tags:
    - terraform
  script:
    - terraform plan

apply_job_for_vault:
  stage: action
  tags:
    - terraform
  script:
    - if [[ "$TERRAFORM_ACTION" == "apply" ]]; then
        terraform apply -auto-approve
      fi
  when: manual
  only:
    variables:
      - $TERRAFORM_ACTION == "apply"

destroy_job_for_vault:
  stage: action
  tags:
    - terraform
  script:
    - if [[ "$TERRAFORM_ACTION" == "destroy" ]]; then
        terraform destroy -auto-approve
      fi
  when: manual
  only:
    variables:
      - $TERRAFORM_ACTION == "destroy"
